### ISSUE TITLE
Improve Design and Styling

### ISSUE THREAD

**Issue by abhishekvalanju** [DSpeichert/cloudvcl#26]
Current Bootstrap and CSS is decent but could use a little tweaking to make it more robust and professional. We will need to mimic Material design style using more Bootstrap and CSS.

Specific parts that need to be addressed:

- Theme - Background, font (style)

- Header- flat

- Help text (hover over with cursor for additional information)
(Ex: Tell the user what an assignment is. Have this message as an alert box. 

https://fezvrasta.github.io/bootstrap-material-design/
^ Proposed Bootstrap theme

**Comment by DSpeichert** [comment]
You can't mimic Material design with Bootstrap unless you use something like https://fezvrasta.github.io/bootstrap-material-design/

That "theme" is not a theme, it's a template and it's an SPA too (Single Page Applications) -> menu scrolls down instead of loading subpages. It's not easily applicable to our project.

**Comment by mitchfeldman** [comment]
What about the template I sent you Ab?

**Comment by DSpeichert** [comment]
@mitchfeldman post it here.

**Comment by mitchfeldman** [comment]
http://getbootstrap.com/examples/jumbotron/

**Comment by abhishekvalanju** [comment]
http://getbootstrap.com/examples/jumbotron/
^ This is what Mitch sent me.

I don't believe it is useful since it's a template and for a single page application

**Comment by mitchfeldman** [comment]
Can we keep what we have and just change the colors and spacing and add elements if necessary?

**Comment by abhishekvalanju** [comment]
Yes, we could do that. But then that's not really improving design and styling now, is it?

**Comment by mitchfeldman** [comment]
Yes it is

**Comment by abhishekvalanju** [comment]
Explain

**Comment by mitchfeldman** [comment]
It would look better than before.

My only problem with the current design is color and spacing, also the tables are too wide. I was hoping we could work together to find a solution for that.

**Comment by abhishekvalanju** [comment]
Color and look will be addressed with the theme Dan provided. I'll leave form spacing and table length to you. These are simple things that you can look up and learn to do in Pycharm.

**Comment by mitchfeldman** [comment]
Why do we need to change the theme?

**Comment by abhishekvalanju** [comment]
http://getbootstrap.com/css/#tables
https://v4-alpha.getbootstrap.com/utilities/spacing/
^ resources for Mitch

**Comment by mitchfeldman** [comment]
Can you do it now?

**Comment by abhishekvalanju** [comment]
No

**Comment by mitchfeldman** [comment]
Y?

**Comment by mitchfeldman** [comment]
Or today

**Comment by mitchfeldman** [comment]
What should I do right now?

**Comment by abhishekvalanju** [comment]
First, I'm at work right now. Second, you can get spacing and table length accomplished now without my theme. Also, in all likelihood, you will bug me to complete the theme and then use it as an excuse to not complete the work assigned to you. Which will essentially make it my job to complete. This would mean you benefit without doing any work. I will not repeat last term and let you coast. So quit bugging me and spamming everyone in the project with emails and get to work on the tables and spacing. I've already given you the resources. I expect the next thing I get from you to be either of two things: a question on something you're having trouble with or a pull request to Daniel.

**Comment by mitchfeldman** [comment]
Oh okay so the theme won't affect tables and spacing at all?

**Comment by abhishekvalanju** [comment]
That's correct

**Comment by abhishekvalanju** [comment]
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.iife.min.js
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.iife.js.maphttps://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.iife.js

**Comment by abhishekvalanju** [comment]
https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp

**Comment by abhishekvalanju** [comment]
http://getbootstrap.com/components/#wells --> Bootstrap wells
http://getbootstrap.com/javascript/#collapse --> use this Bootstrap collapse, silver color regular button with life preserver icon.

Life preserver icon:
"glyphicons glyphicons-life-preserver"
