### ISSUE TITLE
cloud-init functionalities

### ISSUE THREAD

**Issue by Nuyb** [DSpeichert/cloudvcl#31]
Objectives:
- [x] Reread documentation, internalize and understand it
- [x] Prepare a table with proposed functionalities, links to documentation and examples of WORKING scripts
- [x] Order by perceived priority for instructors, invent use cases and provide arguments for the priority

*Do NOT edit this comment. Post new comments in this issue.*

# [Linux](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#)
| Functionality  | Success/Fail | Priority Level | Justification | Use Cases | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| [Install Packages](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install) | Success | High | Programs or software that may be critical to the class are dependent on the successful installation of certain packages. | 1. A lab assignment can be challenging students to view current packages installed on a given instance. |
| [Users and Groups](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#users-and-groups) | Success | High | User management is critical in maintaining a secure system. | 1. Can create a lab that asks students to learn how to carry out different user management tasks such as viewing a list of existing users and groups (or changing permissions) in Ubuntu. |
| [User Scripts](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#scripts-per-boot) | Success  | High | There can be a lot of customization done and content created with this functionality because of its versatility. | 1. Can create labs that ask students to write or understand simple/complex commands using a Bash script and check to see if the commands ran successfully or not in the instance. |
| [Timezone](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#timezone) | Success | Medium | Not a very extensive or important functionality. | 1. Asking students to change the timezone via Bash script could be used as a simple question in a lab assignment. |
| [Hostname](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#set-hostname) | Success | Medium | Not a very extensive or important functionality. | 1. Tasking students to edit the default hostname before launching an Ubuntu instance via Bash script can be a simple question on a lab assignment. |
| [Write Files](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#write-files) | Success | Low | Not very necessary. | 1. Could be used as a lab assignment question like asking students to create a file and see if it was successful or not. |
| [Final Message](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#final-message) | Success | Low | It's not necessary and other functionalities are not dependent on it. | 1. Could be a utility tool such as measuring the uptime like in the example script below.  2. An instructor could add some kind of welcome message/instruction that the students can see when their instance first launches successfully. |

## Scripts
Install Packages Script:
```
#cloud-config

packages: 
- pwgen 
- pastebinit 
```
 Users and Groups Script:
```
#cloud-config

# Add groups to the system
# The following example adds the ubuntu group with members foo and bar and
# the group cloud-users.
groups:
  - cloud-users

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: test
    primary-group: cloud-users
    passwd: passwordtest
```

User Scripts:
```
#!/bin/sh

sudo touch ../var/log/test.txt
```

Write Files Script:
```
#cloud-config

write_files:
  - path: /test.txt
    content: |
      Here is a line.
      Another line is here.
```
Final Message Script:
```
#cloud-config

final_message: "The system is finally up, after $UPTIME seconds"
```
Timezone Script:
```
#cloud-config

timezone: US/Eastern
```
Hostname Script:
```
#cloud-config

hostname: VCL
```
# [Windows](https://cloudbase-init.readthedocs.io/en/latest/userdata.html)

| Functionality  | Success/Fail | Priority Level | Justification | Use Cases | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| [PowerShell Script](http://cloudbase-init.readthedocs.io/en/latest/userdata.html) | Success | High | Windows lab assignments will most likely involve testing various PowerShell scripts since the other functionalities found in Cloudbase-init are not as extensive and explorable. | 1. Can create labs that ask students to write or understand simple/complex commands using a PowerShell script and check to see if the commands ran successfully or not in the Windows instance. | 
| [Timezone](http://cloudbase-init.readthedocs.io/en/latest/userdata.html) | Fail | Low | Not a very extensive or important functionality. | 1. Asking students to change the timezone via PowerShell script could be used as a simple question in a lab assignment. |
| [Hostname](http://cloudbase-init.readthedocs.io/en/latest/userdata.html) | Fail | Low | Not a very extensive or important functionality. | 1. Similar to the Timezone functionality, tasking students to edit the default hostname before launching a Windows instance via PowerShell script can be a simple question on a lab assignment. |

## Scripts
PowerShell Script:
```
#ps1_sysnative 

New-Item c:\VCL\Test -type directory
```
Timezone Script:
```
#cloud-config

set_timezone: Asia/Tbilisi
```

Hostname Script:
```
#cloud-config

set_hostname: newhostname
```

**Comment by syavatkar** [comment]
Scripts: 

Power-State : Make System Shutdown, Reboot 
Status: Script Failed

**Comment by DSpeichert** [comment]
https://yaml-online-parser.appspot.com/

**Comment by DSpeichert** [comment]
Those scripts you copied and pasted demonstrate examples of things you can put it. The data you put didn't work because it doesn't make sense. Nobody said that the examples would work right now. They are examples.

* the package you install (`libpython2.7`) is no longer available at this version (`2.7.3-0ubuntu3.1`). So script is fine but it's impossible to do.
* you cannot create user `foobar` because the group, selinux group, and other things don't exist yet
* you cannot create user group `ubuntu` because users `foo` and `bar` don't exist

You have to read and understand documentation.

**Comment by Nuyb** [comment]
Tested hostname and timezone functionalities in Windows instances but they both failed. Tried digging through the Cloudbase-init log files but couldn't find anything useful. The script that I inputted appears in the log files but there's no indication as to why they failed. I tried Googling both of these issues but couldn't find anything helpful.

**Comment by DSpeichert** [comment]
Test powershell script.

**Comment by Nuyb** [comment]
@DSpeichert tested it and it works

**Comment by DSpeichert** [comment]
Try
```
#cloud-config
timezone: Eastern Standard Time
```
on Windows.

Nobody said timezone names are the same on Windows and Linux.

https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx

**Comment by Nuyb** [comment]
didn't work either

**Comment by DSpeichert** [comment]
Keep trying, or google a working example.

**Comment by syavatkar** [comment]
Cent OS 

| Functionality  | Success/Fail | Priority Level | Justification | Use Cases | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| [Yum Repo](http://cloudbase-init.readthedocs.io/en/latest/userdata.html) | Success | Low| Package managment tool meant to be used CentOs to install RedHat package manager | 1. Can be Used on CentOS to install packages | 


Yum Repo Script:

```
#cloud-config
`#cloud-config
yum_repos:
    # The name of the repository
    epel-testing:
        # Any repository configuration options
        # See: man yum.conf
        #
        # This one is required!
        baseurl: http://download.fedoraproject.org/pub/epel/testing/5/$basearch
        enabled: false
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux 5 - Testing`

```


Windows

```
#cloud-config
set_timezone: America/New_York
```

Cent OS 

| Functionality  | Success/Fail | Priority Level | Justification | Use Cases | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| [CA-Cert](http://cloudinit.readthedocs.io/en/latest/topics/examples.html#configure-an-instances-trusted-ca-certificates) | Failed| Medium| Allows users to add trusted certificates | 1. Can be used for adding organization certificates for possible assignments| 



ca-cert Script

```
#cloud-config
ca-certs:
  # If present and set to True, the 'remove-defaults' parameter will remove
  # all the default trusted CA certificates that are normally shipped with
  # Ubuntu.
  # This is mainly for paranoid admins - most users will not need this
  # functionality.
  remove-defaults: true

  # If present, the 'trusted' parameter should contain a certificate (or list
  # of certificates) to add to the system as trusted CA certificates.
  # Pay close attention to the YAML multiline list syntax.  The example shown
  # here is for a list of multiline certificates.
  trusted: 
  - |
   -----BEGIN CERTIFICATE-----
     MIICCTCCAXKgAwIBAgIBATANBgkqhkiG9w0BAQUFADANMQswCQYDVQQDDAJjYTAe
     Fw0xMDAyMTUxNzI5MjFaFw0xNTAyMTQxNzI5MjFaMA0xCzAJBgNVBAMMAmNhMIGf
     MA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCu7Q40sm47/E1Pf+r8AYb/V/FWGPgc
     b014OmNoX7dgCxTDvps/h8Vw555PdAFsW5+QhsGr31IJNI3kSYprFQcYf7A8tNWu
     1MASW2CfaEiOEi9F1R3R4Qlz4ix+iNoHiUDTjazw/tZwEdxaQXQVLwgTGRwVa+aA
     qbutJKi93MILLwIDAQABo3kwdzA4BglghkgBhvhCAQ0EKxYpUHVwcGV0IFJ1Ynkv
     T3BlblNTTCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwDwYDVR0TAQH/BAUwAwEB/zAd
     BgNVHQ4EFgQUu4+jHB+GYE5Vxo+ol1OAhevspjAwCwYDVR0PBAQDAgEGMA0GCSqG
     SIb3DQEBBQUAA4GBAH/rxlUIjwNb3n7TXJcDJ6MMHUlwjr03BDJXKb34Ulndkpaf
     +GAlzPXWa7bO908M9I8RnPfvtKnteLbvgTK+h+zX1XCty+S2EQWk29i2AdoqOTxb
     hppiGMp0tT5Havu4aceCXiy2crVcudj3NFciy8X66SoECemW9UYDCb9T5D0d
   -----END CERTIFICATE-----
  - |
```

**Comment by DSpeichert** [comment]
Things to implement
======

Linux
====
- Packages to install (needs a model)
- Users to add (needs a model)
- User groups to add (needs a model)
- User scripts (needs a model) + differentiate (once or every boot)
- Timezone (just a column)
- Hostname (just a column, would overwrite default behavior of taking instance name)

Windows
====
- Powershell script

**Comment by Nuyb** [comment]
Questions for @DSpeichert:

1. Can you clarify the relationship details and development process between timezone/hostname & the existing VM definition model? 
2. Can you re-explain the development process for creating new models/form for the functionalities that require one? 
3. We recall that you mentioned to take a look at the relationship that exists between the Course and Assignment Model
4. Once a user selects an options for the form, what form are we generating (YAML) and where is it sent to?
5. Take for example the "packages to install" script. From our understanding we are creating a form for this model. Besides providing an option for what packages the user wants to install, what other options are we providing on the script?

**Comment by DSpeichert** [comment]
@Nuyb Come up with a proposal that works and open a PR with it. Then I'll tell you if that's viable.

**Comment by syavatkar** [comment]
@DSpeichert In terms of a proposal, do you want to specify model data and form entries for each script or actually code it first for your review.

**Comment by DSpeichert** [comment]
Just do it. Show me code.

**Comment by DSpeichert** [comment]
Completed according to new (slightly changed) requirements.
We're dropping the support for defining extra users/groups.

Related work and other functionality previously unplanned in:
* 0a9b700685955ad330eb80b2408f9aa38f3f57cd
* 6e837c6b2c6f477a9fa788ff8921e2d94d1981b9
* e02399d32ddde8973751cc16e3d9d4c290e4e0e3
* eae0ec32a31d7ff1ec33dfbeb94c99ba513659ab
