### ISSUE TITLE
Change default Help text to useful contextual information

### ISSUE THREAD

**Issue by abhishekvalanju** [DSpeichert/cloudvcl#40]
Edit collapsible wells to have useful helpful hints and information for users. This is currently initiated at major process flows such as creating assignments, environments, environment definitions, launching instances and etc. Research how other sites give helpful context to their user and similarly implement.

- [x] assignment_list.html
- [x] course_list.html
- [x] course_detail.html
- [x] environment_definition_detail.html
- [x] environment_definition_list.html 
- [x] assignment_detail.html

Example: For assignment_detail, create a collapsable well. Inside the well, you have to have contextual help such as "By clicking 'Launch an Instance' you are initiating a virtual instance. Please wait for a few minutes once you click the button for setup to be completed".

Note*: Collapsible wells have been made for you in assignment_list.html, course_list.html and environment_definition_detail.html. Edit the context text within them to guide users on how to use the page.

_Acceptance criteria:_ 

1. All pages listed have collapsible wells
2. All wells have context text that is helpful in context to the page its on
3. Text is a minimum a paragraph in length

**Comment by mitchfeldman** [comment]
I think popovers will be better than wells but I can't get them to work. Not sure what I'm missing...

`<button class="btn btn-primary" type="button" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Test test test test"> {% bootstrap_icon "question-sign" %} Help </button>`

I retrieved the code from the bottom of this page: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

**Comment by mitchfeldman** [comment]
`assignment_list.html`
- Before creating a new Assignment, you must create a Course and an Environment Definition. After clicking "Create Assignment" you will be prompted to provide a Name, Description, Start Date, End Date, the corresponding Course, and the corresponding Environment Definition. Click on an Assignment's name to launch a new Environment or view and enter a student's Environment.

`course_list.html`
- Click "Create Course" to create a new Course and add students to that course. Click on a Course title to view active Assignments for that Course or add/remove students in that Course.

`environment_definition_list.html`
- Click "Create Environment Definition" to create a new Environment Definition by simply providing a name for it. By clicking on an Environment Definition name, you will be able to create a VM Definition for that Environment Definition.

`assignment_detail.html`
- By clicking "Update Assignment" you can change the Name, Description, End Date, Course, and/or Environment Definition for this Assignment. By clicking "Launch a new Environment for this Assignment", you will spawn a fresh instance of the Environment (based on the Environment Definition) in a new browser tab. You can also view and enter student's Environments below.

...

**Comment by abhishekvalanju** [comment]
What is this? Are you showing this to get feedback? Cause, it would be nice to see this in the popover/wells so we can judge the appearance.

**Comment by abhishekvalanju** [comment]
Spoke to Dan and he doesn't believe that popovers are a good idea. His reasoning is that it's not obvious that the help text is there.
