### ISSUE TITLE
Instructor Documentation

### ISSUE THREAD

**Issue by abhishekvalanju** [DSpeichert/cloudvcl#45]
- Utilize [Mkdocs](http://www.mkdocs.org/) to create documentation for the Instructor user. 
- [Use case writing guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/)

You will need to create pages and instructions for the Instructor to be able to use the VCL application. This will mean creating documentation to explain certain features, pages, and tools.

For example: 

- Accessing (logging into) Cloud VCL
- Accessing Courses
- Accessing Assignments
- Launching an environment
- Deleting an environment
- Creating, updating and deleting courses
- Creating, updating and deleting assignments
- Creating, updating and deleting environment definitions
- Creating an Assignment

- [x] Read Mkdocs documentation

- [x] Create documentation for the above-listed pages and more pages you come up with

**Comment by syavatkar** [comment]
@Nuyb  Mike it might be a good idea to specify that the link you have provided from ubuntu's site  for installing packages can also be used for installing centOS packages. However, CentOs uses yum package manager to install Rpm packages. Otherwise, you want to include another link for installing CentOS packages.

**Comment by mitchfeldman** [comment]
_Add this Overview directly below the "Instructor Documentation" title._

## Overview
As an instructor, you will use Cloud VCL to administer and facilitate Assignments to students in your Course(s). Every Assignment will utilize a Virtual Environment to complete it. So, before you create an Assignment, you must create an Environment Definition (and corresponding Virtual Machine Definitions) which will determine the parameters of the Virtual Environments that students use for that Assignment. Also before you create an Assignment, you must create a Course.

**Typical Workflow:**

1. Create a Course
2. Add Students to that Course
3. Create an Environment Definition
4. Create VM Definition within that Environment Definition
5. Create an Assignment (assign that Course and Environment Definition to it)
6. Monitor and/or help students complete the Assignment*

*Cloud VCL does not track progress, so it may be best to require proof of completion (screenshots, answer sheet, etc.) from students.
