### ISSUE TITLE
CSV upload page doesn't work

### ISSUE THREAD

**Issue by DSpeichert** [DSpeichert/cloudvcl#46]
```
TypeError at /courses/3/add_students
get() missing 1 required positional argument: 'request'
```

**Comment by syavatkar** [comment]
added request to obj.get() parameters . return super(CourseAddStudents, self).get(request)

**Comment by DSpeichert** [comment]
![image](https://cloud.githubusercontent.com/assets/1254971/25539550/b10baf3c-2c15-11e7-90e6-0d14da7041ca.png)

**Comment by syavatkar** [comment]
Aren't we using Python 3 not Python 2.7.

**Comment by DSpeichert** [comment]
Doesn't matter, we will support both as long as possible. We are actually deploying to Python 2.7.
