### ISSUE TITLE
Selecting a CSV file does not provide any feedback

### ISSUE THREAD

**Issue by DSpeichert** [DSpeichert/cloudvcl#51]
After selecting a file, a selected file's filename should be visible or any other indication that a file was selected. A "Select" button or anything that would hint the need to select a file is also missing.

![image](https://cloud.githubusercontent.com/assets/1254971/25557601/de8d06cc-2ce2-11e7-895f-3eaa31581efd.png)

**Comment by syavatkar** [comment]
![image](https://cloud.githubusercontent.com/assets/6411490/25559778/99544854-2d0f-11e7-84f2-8aeea05b1363.png)

I seem to be having issues with styling using the Django widgets. As you mentioned a few weeks ago, I should be using {% bootstrap_form form %} . But this doesn't seem to be working well with our new material design theme.

**Comment by DSpeichert** [comment]
@abhishekvalanju Can you link the relevant documentation with example - from material theme docs?

**Comment by abhishekvalanju** [comment]
**Relevant Documentation**
Material Theme documentation: https://fezvrasta.github.io/bootstrap-material-design/#fileinput
Bootstrap Elements (scroll down to forms section): http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

**Example** file input form from Material Theme docs: https://fezvrasta.github.io/bootstrap-material-design/#fileinput
