### ISSUE TITLE
Delete Student buttons in course.detail

### ISSUE THREAD

**Issue by mitchfeldman** [DSpeichert/cloudvcl#58]
![image](https://cloud.githubusercontent.com/assets/1210738/25566451/c91e7fa4-2da6-11e7-82b8-86717885f674.png)

As you can see, there are individual delete buttons for each student in a course (which removes them from the course). This should be removed.

**Comment by mitchfeldman** [comment]
Also, anything else we can add to this table? It'll look pretty bare with just names. Email address? User type?

**Comment by DSpeichert** [comment]
If you remove the buttons, how are they going to be removed from the course?

**Comment by mitchfeldman** [comment]
Add/remove button

**Comment by DSpeichert** [comment]
As we spoke today, those need to stay - just provide clearer text on the button explaining that it only removes a student from the course and deletes their environments for this course (if they have any).

@syavatkar I think you forgot to do that - check if they have any environments in the course and delete them when they are deleted from the course.
Task list is therefore:

- [x]  check if they have any environments in the course and delete them when they are deleted from the course
- [ ] add confirmation page for student deletion (again saying it will delete their environments, if any)
- [x] change the delete button text
