### ISSUE TITLE
Cloud-Init Customization Form Questions

### ISSUE THREAD

**Issue by syavatkar** [DSpeichert/cloudvcl#67]
Cloud-Init, Bash Form Questions 

Some fields that were recently added for VMDefinition include powershell_script, timezone, and hostname. Would  PackageUpdate, PackageUpgrade , and PackageReboot be seperate Boolean fields that could be added to the VMDefinition model? 

Since powershell script is set as an option in VMDefinition, shouldn’t script per boot, and script per instance should also be set as fields for the VMdefinition form.

Once a user submits, a cloud-init and bash script in the VM definition form, the mime multi part message, the mime-generated standard message can include both the following scripts as one string right?

You mentioned earlier that I should be testing the mime-generated standard message in Openstack Horizon under the scripts field. How do I know if the mime-generated standard message is correct? Is there a validator for mime messages?

**Comment by DSpeichert** [comment]
Closing as you were reassigned.
