### ISSUE TITLE
Accessing restricted functionality for student account

### ISSUE THREAD

**Issue by syavatkar** [DSpeichert/cloudvcl#83]
When a student attempts to access create assignment functionality through https://cloudvcl.cci.drexel.edu/assignments/create, should they be directed to the drexel connect login screen or have a message displaying a 403 error. On my laptop, I get redirected to the Drexel Connect Login page. But, when I use a machine on the drexel domain, I get a 403 error displaying a message "You don't have permission to access /assignments/create on this server."  I have included a screenshot below. 

![image](https://cloud.githubusercontent.com/assets/6411490/25912193/71dd7a16-3584-11e7-90a9-4d3efb65f93d.png)

**Comment by syavatkar** [comment]
![image](https://cloud.githubusercontent.com/assets/6411490/25913242/0d3d8106-3588-11e7-9799-e9f52e47c6cb.png) .  Another message I received using a machine on the Drexel domain when attempting to access https://cloudvcl.cci.drexel.edu/assignments/1/update with a student account. Instead for this one, I get a different message displaying "You don't have permission to access /login"

**Comment by DSpeichert** [comment]
@abhishekvalanju please verify

**Comment by abhishekvalanju** [comment]
@syavatkar I tested as an instructor and it works fine. I mean wouldn't it make sense that it would work for a student since a student doesn't have permission to edit/update an assignment.

**Comment by DSpeichert** [comment]
It's proper behavior, you can't get access to the login page with a redirect to a page you can't access.
