### ISSUE TITLE
CentOS installed packages failure

### ISSUE THREAD

**Issue by syavatkar** [DSpeichert/cloudvcl#88]
Specifed Packages in VM Definition form to install and none of the following packages were installed for CentOS

package name specified was pastebinit. I used rpm - q packagename to check if the following package was installed.

@Nuyb Can you retest to confirm bug?

**Comment by DSpeichert** [comment]
Try disabling package updates and testing again. Most likely you didn't wait long enough.

**Comment by Nuyb** [comment]
Tested `abrt` package and it was successful for CentOS. I checked by using `rpm -q abrt` (result: pictured below) and `sudo yum install abrt` (result: already installed) commands. 

![screen shot 2017-05-21 at 8 23 53 pm](https://cloud.githubusercontent.com/assets/6350986/26288604/b3d5a2d0-3e63-11e7-9cc9-415f3f7bebd2.png)
